using System.Collections.Generic;

namespace BlazorAIChatBot.Server.Helpers
{
    public static class EntityCodeMapper
    {
        private static readonly Dictionary<string, string> EntityCodeMap = new(StringComparer.OrdinalIgnoreCase)
        {
            { "Afghanistan", "AFG" },
            { "Africa", "AFR" },
            { "Albania", "ALB" },
            { "Algeria", "DZA" },
            { "American Samoa", "ASM" },
            { "Angola", "AGO" },
            { "Antigua and Barbuda", "ATG" },
            { "Argentina", "ARG" },
            { "Armenia", "ARM" },
            { "Aruba", "ABW" },
            { "ASEAN", "ASN" },
            { "Asia", "ASI" },
            { "Australia", "AUS" },
            { "Austria", "AUT" },
            { "Azerbaijan", "AZE" },
            { "Bahamas", "BHS" },
            { "Bahrain", "BHR" },
            { "Bangladesh", "BGD" },
            { "Barbados", "BRB" },
            { "Belarus", "BLR" },
            { "Belgium", "BEL" },
            { "Belize", "BLZ" },
            { "Benin", "BEN" },
            { "Bhutan", "BTN" },
            { "Bolivia", "BOL" },
            { "Bosnia Herzegovina", "BIH" },
            { "Botswana", "BWA" },
            { "Brazil", "BRA" },
            { "Brunei Darussalam", "BRN" },
            { "Bulgaria", "BGR" },
            { "Burkina Faso", "BFA" },
            { "Burundi", "BDI" },
            { "Cabo Verde", "CPV" },
            { "Cambodia", "KHM" },
            { "Cameroon", "CMR" },
            { "Canada", "CAN" },
            { "Cayman Islands", "CYM" },
            { "Central African Republic", "CAF" },
            { "Chad", "TCD" },
            { "Chile", "CHL" },
            { "China", "CHN" },
            { "Colombia", "COL" },
            { "Comoros", "COM" },
            { "Congo", "COG" },
            { "Congo (DRC)", "COD" },
            { "Cook Islands (the)", "COK" },
            { "Costa Rica", "CRI" },
            { "Cote d'Ivoire", "CIV" },
            { "Croatia", "HRV" },
            { "Cuba", "CUB" },
            { "Cyprus", "CYP" },
            { "Czechia", "CZE" },
            { "Denmark", "DNK" },
            { "Djibouti", "DJI" },
            { "Dominica", "DMA" },
            { "Dominican Republic", "DOM" },
            { "Ecuador", "ECU" },
            { "Egypt", "EGY" },
            { "El Salvador", "SLV" },
            { "Equatorial Guinea", "GNQ" },
            { "Eritrea", "ERI" },
            { "Estonia", "EST" },
            { "Eswatini", "SWZ" },
            { "Ethiopia", "ETH" },
            { "EU", "EUR" },
            { "Europe", "EUR" },
            { "Falkland Islands [Malvinas]", "FLK" },
            { "Faroe Islands", "FRO" },
            { "Fiji", "FJI" },
            { "Finland", "FIN" },
            { "France", "FRA" },
            { "French Guiana", "GUF" },
            { "French Polynesia", "PYF" },
            { "G20", "G20" },
            { "G7", "G7" },
            { "Gabon", "GAB" },
            { "Gambia", "GMB" },
            { "Georgia", "GEO" },
            { "Germany", "DEU" },
            { "Ghana", "GHA" },
            { "Greece", "GRC" },
            { "Greenland", "GRL" },
            { "Grenada", "GRD" },
            { "Guadeloupe", "GLP" },
            { "Guam", "GUM" },
            { "Guatemala", "GTM" },
            { "Guinea", "GIN" },
            { "Guinea-Bissau", "GNB" },
            { "Guyana", "GUY" },
            { "Haiti", "HTI" },
            { "Honduras", "HND" },
            { "Hong Kong", "HKG" },
            { "Hungary", "HUN" },
            { "Iceland", "ISL" },
            { "India", "IND" },
            { "Indonesia", "IDN" },
            { "Iran", "IRN" },
            { "Iraq", "IRQ" },
            { "Ireland", "IRL" },
            { "Israel", "ISR" },
            { "Italy", "ITA" },
            { "Jamaica", "JAM" },
            { "Japan", "JPN" },
            { "Jordan", "JOR" },
            { "Kazakhstan", "KAZ" },
            { "Kenya", "KEN" },
            { "Kiribati", "KIR" },
            { "Kosovo", "XKX" },
            { "Kuwait", "KWT" },
            { "Kyrgyzstan", "KGZ" },
            { "Lao", "LAO" },
            { "Latin America and Caribbean", "LAC" },
            { "Latvia", "LVA" },
            { "Lebanon", "LBN" },
            { "Lesotho", "LSO" },
            { "Liberia", "LBR" },
            { "Libya", "LBY" },
            { "Lithuania", "LTU" },
            { "Luxembourg", "LUX" },
            { "Macao", "MAC" },
            { "Madagascar", "MDG" },
            { "Malawi", "MWI" },
            { "Malaysia", "MYS" },
            { "Maldives", "MDV" },
            { "Mali", "MLI" },
            { "Malta", "MLT" },
            { "Martinique", "MTQ" },
            { "Mauritania", "MRT" },
            { "Mauritius", "MUS" },
            { "Mexico", "MEX" },
            { "Middle East", "MEA" },
            { "Moldova", "MDA" },
            { "Mongolia", "MNG" },
            { "Montenegro", "MNE" },
            { "Montserrat", "MSR" },
            { "Morocco", "MAR" },
            { "Mozambique", "MOZ" },
            { "Myanmar", "MMR" },
            { "Namibia", "NAM" },
            { "Nauru", "NRU" },
            { "Nepal", "NPL" },
            { "Netherlands", "NLD" },
            { "New Caledonia", "NCL" },
            { "New Zealand", "NZL" },
            { "Nicaragua", "NIC" },
            { "Niger", "NER" },
            { "Nigeria", "NGA" },
            { "North America", "NAM" },
            { "North Korea", "PRK" },
            { "North Macedonia", "MKD" },
            { "Norway", "NOR" },
            { "Oceania", "OCE" },
            { "OECD", "OECD" },
            { "Oman", "OMN" },
            { "Pakistan", "PAK" },
            { "Palestine, State of", "PSE" },
            { "Panama", "PAN" },
            { "Papua New Guinea", "PNG" },
            { "Paraguay", "PRY" },
            { "Peru", "PER" },
            { "Poland", "POL" },
            { "Portugal", "PRT" },
            { "Puerto Rico", "PRI" },
            { "Qatar", "QAT" },
            { "Reunion", "REU" },
            { "Romania", "ROU" },
            { "Russia", "RUS" },
            { "Rwanda", "RWA" },
            { "Saint Kitts and Nevis", "KNA" },
            { "Saint Lucia", "LCA" },
            { "Saint Pierre and Miquelon", "SPM" },
            { "Saint Vincent and the Grenadines", "VCT" },
            { "Samoa", "WSM" },
            { "Sao Tome and Principe", "STP" },
            { "Saudi Arabia", "SAU" },
            { "Senegal", "SEN" },
            { "Serbia", "SRB" },
            { "Seychelles", "SYC" },
            { "Sierra Leone", "SLE" },
            { "Singapore", "SGP" },
            { "Slovakia", "SVK" },
            { "Slovenia", "SVN" },
            { "Solomon Islands", "SLB" },
            { "Somalia", "SOM" },
            { "South Africa", "ZAF" },
            { "South Korea", "KOR" },
            { "South Sudan", "SSD" },
            { "Spain", "ESP" },
            { "Sri Lanka", "LKA" },
            { "Sudan", "SDN" },
            { "Suriname", "SUR" },
            { "Sweden", "SWE" },
            { "Switzerland", "CHE" },
            { "Syria", "SYR" },
            { "Taiwan", "TWN" },
            { "Tajikistan", "TJK" },
            { "Tanzania, the United Republic of", "TZA" },
            { "Thailand", "THA" },
            { "The Philippines", "PHL" },
            { "Togo", "TGO" },
            { "Tonga", "TON" },
            { "Trinidad and Tobago", "TTO" },
            { "Tunisia", "TUN" },
            { "Türkiye", "TUR" },
            { "Turkmenistan", "TKM" },
            { "Turks and Caicos Islands", "TCA" },
            { "Uganda", "UGA" },
            { "Ukraine", "UKR" },
            { "United Arab Emirates", "ARE" },
            { "United Kingdom", "GBR" },
            { "United States", "USA" },
            { "Uruguay", "URY" },
            { "Uzbekistan", "UZB" },
            { "Vanuatu", "VUT" },
            { "Venezuela", "VEN" },
            { "Viet Nam", "VNM" },
            { "Virgin Islands (British)", "VGB" },
            { "Virgin Islands (U.S.)", "VIR" },
            { "World", "WLD" },
            { "Yemen", "YEM" },
            { "Zambia", "ZMB" }
        };

        public static string? GetEntityCode(string entity)
        {
            return EntityCodeMap.TryGetValue(entity, out var code) ? code : null;
        }
    }
}